name = "CobblemonQuetta"
author = "Hercide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50258a6adf90fda077caac6cf479a8638deb9488a8428d6af6ece6bc1d81c512"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "resourcepacks"
