name = "CobblemonQuetta"
author = "Hercide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8369a511e069bb8e7c14cb222ce41b2e5df464c5286294acb52c98caac0a3992"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "resourcepacks"
