name = "CobblemonQuetta"
author = "Hercide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd2264de95899c34c6e551ab4eab3eceb3456f7dd4e54952aff234a928146df7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "resourcepacks"
